name: editor-config
type: php
docroot: ""
php_version: "8.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
composer_version: "2"
omit_containers: [db, dba, ddev-ssh-agent]
web_environment:
  - PHP_IDE_CONFIG=serverName=DDEV
