name: "Tagged Release"

on:
    push:
        tags:
            - "*"

jobs:
    tagged-release:
        name: "Create Release"
        runs-on: "ubuntu-latest"

        steps:
        - uses: actions/checkout@v2

        - name: Setup PHP
          uses: "shivammathur/setup-php@v2"
          with:
            php-version: "7.4"
            ini-values: "phar.readonly=0"

        - name: Validate composer.json and composer.lock
          run: composer validate

        - name: Cache Composer packages
          id: composer-cache
          uses: actions/cache@v2
          with:
            path: vendor
            key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
                ${{ runner.os }}-php-

        - name: Composer install
          uses: "ramsey/composer-install@v1"

        - name: Get latest release version number
          id: get_version
          uses: battila7/get-version-action@v2

        - name: Build PHAR
          run: |
              composer run compile

        - name: Test PHAR
          run: |
              chmod +x ec-${{ steps.get_version.outputs.version }}.phar
              ./ec-${{ steps.get_version.outputs.version }}.phar --help
              ./ec-${{ steps.get_version.outputs.version }}.phar

        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              prerelease: false
              files: |
                  *.phar
